### ISSUE TITLE
Docker Install Problems

### ISSUE THREAD

**Issue by dotnjet** [SFTtech/abrechnung#173]
I have problems installing the Docker Project on my Synology NAS.
I have followed the instructions(https://abrechnung.readthedocs.io/en/latest/usage/installation.html#docker-compose) but always get the same error on the API Image.

```
Messages:
abrechnung-api-1       | Traceback (most recent call last):
abrechnung-api-1       |   File "/usr/local/bin/abrechnung", line 8, in <module>
abrechnung-api-1       |     sys.exit(main())
abrechnung-api-1       |   File "/usr/share/abrechnung/abrechnung/__main__.py", line 72, in main
abrechnung-api-1       |     asyncio.run(subcommand_object.run())
abrechnung-api-1       |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
abrechnung-api-1       |     return loop.run_until_complete(main)
abrechnung-api-1       |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
abrechnung-api-1       |     return future.result()
abrechnung-api-1       |   File "/usr/share/abrechnung/abrechnung/database/cli.py", line 103, in run
abrechnung-api-1       |     db_pool = await create_db_pool(self.config)
abrechnung-api-1       |   File "/usr/share/abrechnung/abrechnung/database/database.py", line 52, in create_db_pool
abrechnung-api-1       |     return await asyncpg.create_pool(**pool_args)
abrechnung-api-1       |   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 409, in _async__init__
abrechnung-api-1       |     await self._initialize()
abrechnung-api-1       |   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 437, in _initialize
abrechnung-api-1       |     await first_ch.connect()
abrechnung-api-1       |   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 129, in connect
abrechnung-api-1       |     self._con = await self._pool._get_new_connection()
abrechnung-api-1       |   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 514, in _get_new_connection
abrechnung-api-1       |     con = await connection.connect(
abrechnung-api-1       |   File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2114, in connect
abrechnung-api-1       |     return await connect_utils._connect(
abrechnung-api-1       |   File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 1011, in _connect
abrechnung-api-1       |     raise last_error or exceptions.TargetServerAttributeNotMatched(
abrechnung-api-1       |   File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 982, in _connect
abrechnung-api-1       |     conn = await _connect_addr(
abrechnung-api-1       |   File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 808, in _connect_addr
abrechnung-api-1       |     return await __connect_addr(params, timeout, True, *args)
abrechnung-api-1       |   File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 860, in __connect_addr
abrechnung-api-1       |     tr, pr = await compat.wait_for(connector, timeout=timeout)
abrechnung-api-1       |   File "/usr/local/lib/python3.10/site-packages/asyncpg/compat.py", line 60, in wait_for
abrechnung-api-1       |     return await asyncio.wait_for(fut, timeout)
abrechnung-api-1       |   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
abrechnung-api-1       |     return fut.result()
abrechnung-api-1       |   File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 719, in _create_ssl_connection
abrechnung-api-1       |     tr, pr = await loop.create_connection(
abrechnung-api-1       |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1036, in create_connection
abrechnung-api-1       |     infos = await self._ensure_resolved(
abrechnung-api-1       |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1418, in _ensure_resolved
abrechnung-api-1       |     return await loop.getaddrinfo(host, port, family=family, type=type,
abrechnung-api-1       |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
abrechnung-api-1       |     return await self.run_in_executor(
abrechnung-api-1       |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
abrechnung-api-1       |     result = self.fn(*self.args, **self.kwargs)
abrechnung-api-1       |   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
abrechnung-api-1       |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
abrechnung-api-1       | socket.gaierror: [Errno -2] Name does not resolve
abrechnung-api-1       | Traceback (most recent call last):
abrechnung-api-1       |   File "/entrypoint.py", line 76, in <module>
abrechnung-api-1       |     subprocess.run("abrechnung db migrate", shell=True, check=True)
abrechnung-api-1       |   File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
abrechnung-api-1       |     raise CalledProcessError(retcode, process.args,
abrechnung-api-1       | subprocess.CalledProcessError: Command 'abrechnung db migrate' returned non-zero exit status 1.
abrechnung-mailer-1 exited with code 1
```

May somebody can help.

**Comment by mikonse** [comment]
I think the issue is that you have no postgres database running.
The default prod docker-compose file does not include a database since we'd recommend using an external postgres since it's easy to mess up when running postgres within a container. 

You can take a look at the `docker-compose.devel.yaml` though, which includes a postgres database within the docker-compose file. If you adapt the docker-compose prod to include the postgres container and set the DB_HOST variable for the other containers accordingly you should be able to run the api container normally.

**Comment by dotnjet** [comment]
Many thanks. Sorry for the late answer. Will test a.s.a.p.  
Great support!

**Comment by TheJJ** [comment]
I'll close this for now. You can also come by in the chatroom for more interactive help :)
