### ISSUE TITLE
Docker setup - env variables from .env not being loaded

### ISSUE THREAD

**Issue by maciejewiczow** [SFTtech/abrechnung#205]
Hi, I am trying to set-up Abrechnung using the provided docker-compose files (with slight modifications). However the `api` container keeps exiting and I see a similar message in the docker logs:
```log
generating config
config done
migrating
Traceback (most recent call last):

  File "/usr/local/bin/abrechnung", line 8, in <module>
    sys.exit(main())

  File "/usr/share/abrechnung/abrechnung/cli/main.py", line 64, in main
    cli()

  File "/usr/share/abrechnung/abrechnung/cli/main.py", line 36, in get_config
    config = read_config(config_path)

  File "/usr/share/abrechnung/abrechnung/config.py", line 61, in read_config
    config = Config(**yaml.safe_load(content))

  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)

pydantic_core._pydantic_core.ValidationError: 2 validation errors for Config
api.secret_key
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
database.dbname
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type

Traceback (most recent call last):
  File "/entrypoint.py", line 73, in <module>
    subprocess.run("abrechnung db migrate", shell=True, check=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'abrechnung db migrate' returned non-zero exit status 1.
```
From what I can tell from this error some envs are missing, but I don't know how to load them properly. My `.env` file looks as follows:
```env
ABRECHNUNG_SERVICE__URL="http://localhost:2137"
ABRECHNUNG_SERVICE__API_URL="https://localhost:2137/api"
ABRECHNUNG_SERVICE__NAME="Abrechnung"
ABRECHNUNG_DATABASE__HOST="db"
ABRECHNUNG_DATABASE__USER="abrechnung"
ABRECHNUNG_DATABASE__DBNAME="abrechnung"
ABRECHNUNG_DATABASE__PASSWORD="[REDACTED]"

ABRECHNUNG_API__SECRET_KEY="[REDACTED]"
ABRECHNUNG_API__PORT=2137
ABRECHNUNG_API__ID="default"

ABRECHNUNG_REGISTRATION__ENABLED=false

ABRECHNUNG_EMAIL__ADDRESS=finansemieszkanie@gmail.com
ABRECHNUNG_EMAIL__HOST=imap.gmail.com
ABRECHNUNG_EMAIL__PORT=993
ABRECHNUNG_EMAIL__MODE=smtp-ssl # use this in production, remove line above
ABRECHNUNG_EMAIL__AUTH__USERNAME=finansemieszkanie@gmail.com
ABRECHNUNG_EMAIL__AUTH__PASSWORD='[REDACTED]'

POSTGRES_USER="abrechnung"
POSTGRES_PASSWORD="[REDACTED]" # use the same as DB_PASSWORD
POSTGRES_DATABASE="abrechnung" # use the same as DB_NAME
```
The variables that should correspond to the ones specified in the error from the logs are present. 
For completeness sake here is my modified `docker-compose.yml`:
```yml
services:
  api:
    extends:
      file: docker-compose.base.yml
      service: api
    image: quay.io/abrechnung/api:latest-release
    env_file: .env

  frontend:
    image: quay.io/abrechnung/frontend:latest-release
    depends_on:
      api:
        condition: service_healthy
    links:
      - api

  mailer:
    extends:
      file: docker-compose.base.yml
      service: mailer
    image: quay.io/abrechnung/api:latest-release
    links:
      - db
      - api

  cron:
    extends:
      file: docker-compose.base.yml
      service: cron
    image: quay.io/abrechnung/api:latest-release
    links:
      - api

  db:
    image: docker.io/postgres:14-alpine
    env_file: .env
    healthcheck:
      test: [ "CMD", "/usr/local/bin/pg_isready" ]
      start_period: 10s
    volumes:
      - "./data/pg:/var/lib/postgresql/data"
```
and `docker-compose.base.yml`
```yml
services:
  api:
    command: api
    env_file: .env
    expose:
      - "2137:2137"
    healthcheck:
      test:
        [
          "CMD",
          "/usr/bin/curl",
          "--connect-timeout",
          "10",
          "--silent",
          "http://127.0.0.1:2137/"
        ]

  mailer:
    extends:
      service: api
    command: mailer
    healthcheck:
      disable: true

  cron:
    extends:
      service: api
    command: cron
    healthcheck:
      disable: true
```
Any help would be greatly appreciated 😅

**Comment by mikonse** [comment]
Could you retest using the latest release which was just published (v0.13.1). From my local testing with the config you've provided the error should be fixed.

**Comment by maciejewiczow** [comment]
Okay, now it seems to be working all right, thank you very much. Now something else is not working, but maybe this issue is not the place to discuss that, because it does not seem to be connected.

**Comment by mikonse** [comment]
All right, then I'll close this one. If the other issue still persists feel free to open another one.
